/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: src/sanity/extract.json
export type Schedule = {
  _id: string;
  _type: "schedule";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  isOpen?: boolean;
  availabilityRange?: {
    from?: string;
    to?: string;
  };
};

export type Review = {
  _id: string;
  _type: "review";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  clientReview?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Suit = {
  _id: string;
  _type: "suit";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  versions?: Array<{
    versionName?: string;
    price?: number;
    fullDescription?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    images?: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }>;
    _type: "version";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Schedule
  | Review
  | SanityImageCrop
  | SanityImageHotspot
  | Suit
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/lib/queries.ts
// Variable: SUITS_CARD_QUERY
// Query: *[_type == "suit" && defined(slug.current)]  | order(_createdAt desc) {    _id,    _createdAt,    name,    slug,    versions[0]{      images[0]{        asset->{          url        }      }    }  }
export type SUITS_CARD_QUERY_RESULT = Array<{
  _id: string;
  _createdAt: string;
  name: string | null;
  slug: Slug | null;
  versions: {
    images: {
      asset: {
        url: string | null;
      } | null;
    } | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: REVIEWERS_QUERY
// Query: *[_type == "review"]  | order(_createdAt desc)[0...3]{    _id,    name,    clientReview,    image{      asset->{        url      }    }  }
export type REVIEWERS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  clientReview: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  image: {
    asset: {
      url: string | null;
    } | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: SUITS_CARD_PAGINATED_QUERY
// Query: {  "products": *[_type == "suit"]     | order(publishedAt desc)     [$start...$end]{      _id,    _createdAt,    name,    slug,    versions[0]{      images[0]{        asset->{          url        }      }    }  },  "total": count(*[_type == "suit"])}
export type SUITS_CARD_PAGINATED_QUERY_RESULT = {
  products: Array<{
    _id: string;
    _createdAt: string;
    name: string | null;
    slug: Slug | null;
    versions: {
      images: {
        asset: {
          url: string | null;
        } | null;
      } | null;
    } | null;
  }>;
  total: number;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "suit" && defined(slug.current)]\n  | order(_createdAt desc) {\n    _id,\n    _createdAt,\n    name,\n    slug,\n    versions[0]{\n      images[0]{\n        asset->{\n          url\n        }\n      }\n    }\n  }\n': SUITS_CARD_QUERY_RESULT;
    '\n  *[_type == "review"]\n  | order(_createdAt desc)[0...3]{\n    _id,\n    name,\n    clientReview,\n    image{\n      asset->{\n        url\n      }\n    }\n  }\n': REVIEWERS_QUERY_RESULT;
    '\n{\n  "products": *[_type == "suit"] \n    | order(publishedAt desc) \n    [$start...$end]{\n      _id,\n    _createdAt,\n    name,\n    slug,\n    versions[0]{\n      images[0]{\n        asset->{\n          url\n        }\n      }\n    }\n  },\n  "total": count(*[_type == "suit"])\n}\n': SUITS_CARD_PAGINATED_QUERY_RESULT;
  }
}
